// <auto-generated />
using BusinessAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAPI.Migrations
{
    [DbContext(typeof(BusinessAPIContext))]
    [Migration("20230819024308_reSeedData")]
    partial class reSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessAPI.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("longtext");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.Property<string>("ShopName")
                        .HasColumnType("longtext");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            LocationName = "New Albany",
                            Rating = 10,
                            RestaurantName = "Fox in the Snow Cafe",
                            Review = "Best Cafe Art in town"
                        },
                        new
                        {
                            BusinessId = 2,
                            LocationName = "WesterVille",
                            Rating = 9,
                            RestaurantName = "Kitchen Social",
                            Review = "Amazing chicken and waffles"
                        },
                        new
                        {
                            BusinessId = 3,
                            LocationName = "Dublin",
                            Rating = 8,
                            RestaurantName = "Kitchen Social",
                            Review = "Amazing chicken and waffles"
                        },
                        new
                        {
                            BusinessId = 4,
                            LocationName = "High St",
                            Rating = 8,
                            RestaurantName = "Zencha Cafe",
                            Review = "Masala Chai waffles were the lightest crispiest waffles ever chicken dumping looked ordinary but tasted heavenly"
                        },
                        new
                        {
                            BusinessId = 5,
                            LocationName = "Columbus",
                            Rating = 3,
                            RestaurantName = "Mozart's",
                            Review = "Authentic Tea Experience in Columbus"
                        },
                        new
                        {
                            BusinessId = 6,
                            LocationName = "TownsFair Way",
                            Rating = 10,
                            RestaurantName = " Northstar Café ",
                            Review = "This place has some of the best healthy food that I have ever tasted."
                        },
                        new
                        {
                            BusinessId = 7,
                            LocationName = "Easton Station",
                            Rating = 9,
                            RestaurantName = " Mitchell's Ocean Club",
                            Review = "Best Seafood in town"
                        },
                        new
                        {
                            BusinessId = 8,
                            LocationName = "Gahanna,",
                            Rating = 7,
                            RestaurantName = " The Morning Ritual",
                            Review = "Great coffee & pastries, baked apple cinnamon roll is a must!"
                        },
                        new
                        {
                            BusinessId = 9,
                            LocationName = "Westerville",
                            Rating = 6,
                            RestaurantName = " Java Central Café",
                            Review = "Best cold brew nitro in town! Everything is awesome, especially the people."
                        },
                        new
                        {
                            BusinessId = 10,
                            LocationName = "Cleavland",
                            Rating = 10,
                            RestaurantName = " Safari Coffee House",
                            Review = "One of the best Somali restaurants In Columbus"
                        },
                        new
                        {
                            BusinessId = 11,
                            LocationName = "Kossuth St",
                            Rating = 8,
                            Review = "Popular mall. Good selection of stores. Clean.",
                            ShopName = "Tigertree"
                        },
                        new
                        {
                            BusinessId = 12,
                            LocationName = "Olenrangy River Rd",
                            Rating = 4,
                            Review = "Nice shops, but the traffic and parking are awful.",
                            ShopName = "Lennox Town Center"
                        },
                        new
                        {
                            BusinessId = 13,
                            LocationName = "Grandview Ave",
                            Rating = 6,
                            Review = "Fantastic assortment of unique pieces, and a friendly group of associates!",
                            ShopName = "Vernacular - Grandview"
                        },
                        new
                        {
                            BusinessId = 14,
                            LocationName = "Channingway Center Dr",
                            Rating = 7,
                            Review = "Large antique mall with many different sellers and reasonable pricing.",
                            ShopName = "Heritage Square Antique Mall"
                        },
                        new
                        {
                            BusinessId = 15,
                            LocationName = "Grandview Ave,",
                            Rating = 5,
                            Review = "Upscale market. Huge variety.",
                            ShopName = "North Market Downtown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
